version: 2.1
orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2
jobs:
  test:
    executor:
      name: node/default
      tag: '12.16'
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: npm run test -- --ci --maxWorkers=1 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - slack/status:
          only_for_branches: master

workflows:
  workflow:
    jobs:
      - test:
          context:
            - test
